

from __future__ import annotations

from typing import Any

import structlog
from fastapi import Depends, Header, HTTPException, Query

from cancer_claw.services.identity import repo
from cancer_claw.services.identity.security import TokenError, decode_access_token, generate_secret
from cancer_claw.config import settings
from cancer_claw.db import get_read_db

logger = structlog.get_logger()

LOCAL_SUPERUSER: dict[str, Any] = {
    "id": "local",
    "username": "local",
    "email": "",
    "display_name": "本地用户",
    "role": repo.ROLE_ADMIN,
    "status": "active",
    "created_at": None,
    "updated_at": None,
}

def get_auth_secret() -> str:

    if not settings.auth.secret:
        settings.auth.secret = generate_secret()
        logger.warning("auth_secret_autogenerated_dev_only")
    return settings.auth.secret

def is_admin(user: dict[str, Any]) -> bool:
    return user.get("role") == repo.ROLE_ADMIN

async def get_current_user(
    authorization: str | None = Header(default=None),
    access_token: str | None = Query(
        default=None,
        description="备用令牌位（供无法设置请求头的浏览器 <img>/下载链接使用）",
    ),
) -> dict[str, Any]:

    if not settings.auth.enabled:
        return dict(LOCAL_SUPERUSER)

    token = ""
    if authorization and authorization.lower().startswith("bearer "):
        token = authorization[7:].strip()
    elif access_token:
        token = access_token.strip()
    if not token:
        raise HTTPException(status_code=401, detail="未提供登录凭证")

    try:
        payload = decode_access_token(token, secret=get_auth_secret())
    except TokenError as e:
        raise HTTPException(status_code=401, detail=f"登录凭证无效: {e}") from e

    user_id = payload.get("sub")
    if not user_id:
        raise HTTPException(status_code=401, detail="登录凭证缺少主体")

    user = await repo.get_user_by_id(str(user_id))
    if not user:
        raise HTTPException(status_code=401, detail="用户不存在")
    if user.get("status") != "active":
        raise HTTPException(status_code=403, detail="账号已被禁用")


    try:
        user["permissions"] = await repo.get_effective_permissions(user)
    except Exception:

        user["permissions"] = []
    return user

async def require_admin(
    user: dict[str, Any] = Depends(get_current_user),
) -> dict[str, Any]:
    if not is_admin(user):
        raise HTTPException(status_code=403, detail="需要管理员权限")
    return user

def has_permission(user: dict[str, Any], perm_key: str) -> bool:

    if is_admin(user):
        return True
    return perm_key in (user.get("permissions") or [])

def require_permission(perm_key: str):


    async def _dep(
        user: dict[str, Any] = Depends(get_current_user),
    ) -> dict[str, Any]:
        if not has_permission(user, perm_key):
            raise HTTPException(status_code=403, detail="没有执行该操作的权限")
        return user

    return _dep

def require_feature(feature: str):


    async def _dep() -> None:
        enabled = bool(getattr(settings.features, feature, False))
        if not enabled:
            raise HTTPException(status_code=403, detail="该功能当前未开放")

    return _dep

async def _load_project(project_id: str) -> dict[str, Any] | None:

    db = await get_read_db()
    cur = await db.execute(
        "SELECT id, owner_id FROM projects WHERE id = ?", (project_id,)
    )
    row = await cur.fetchone()
    if not row:
        return None
    return {"id": row[0], "owner_id": row[1]}

async def compute_project_role(
    user: dict[str, Any], project_id: str
) -> tuple[dict[str, Any] | None, str | None]:

    project = await _load_project(project_id)
    if project is None:
        return None, None
    if is_admin(user):
        return project, "owner"
    if project.get("owner_id") and project["owner_id"] == user["id"]:
        return project, "owner"
    member_role = await repo.get_member_role(project_id, user["id"])
    return project, member_role

class ProjectContext(dict):
    pass


async def _resolve_access(
    project_id: str, user: dict[str, Any], *, need: str
) -> ProjectContext:

    project, role = await compute_project_role(user, project_id)
    if project is None or role is None:
        raise HTTPException(status_code=404, detail=f"项目 {project_id} 不存在")

    if need == "write" and role == "viewer":
        raise HTTPException(status_code=403, detail="只读成员无写入权限")
    if need == "manage" and role != "owner":
        raise HTTPException(status_code=403, detail="仅项目所有者或管理员可管理")

    return ProjectContext(user=user, project_id=project_id, role=role, project=project)

async def require_project_read(
    project_id: str, user: dict[str, Any] = Depends(get_current_user)
) -> ProjectContext:

    return await _resolve_access(project_id, user, need="read")

async def require_project_write(
    project_id: str, user: dict[str, Any] = Depends(get_current_user)
) -> ProjectContext:

    return await _resolve_access(project_id, user, need="write")

async def require_project_manage(
    project_id: str, user: dict[str, Any] = Depends(get_current_user)
) -> ProjectContext:

    return await _resolve_access(project_id, user, need="manage")
